language: node_js
node_js: 12.14

install:
  - npm install
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "acshmily"
  - git config user.email "shmily#newbie.town"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - backup
env:
 global:
   - GH_REF: github.com/acshmily/acshmily.github.io.git
