menu:
  Home: /
  Archives: archives
  cate: cate
  page:
    归档: archives
    专题: categories
    友链: friendlinks
    关于: life
    搜索: search

sidePic: https://tva1.sinaimg.cn/large/007S8ZIlgy1ggdmi6yapmj30dw0zk0wm.jpg
avatar: https://avatars1.githubusercontent.com/u/5118125?s=460&u=25ba96507995d359cb1190c672315d9b0fbb23fb&v=4

excerpt_link: 继续阅读
excerpt: 200

social:
  twitter: false
  github: true
  weibo: false
  yuque: false
  rss: true

twitter:
  username:

github:
  username: acshmily

weibo:
  username:

yuque:
  username:

# https://www.leancloud.cn/
valine:
  appId:
  appKey:

# https://web.umeng.com/
# umeng: 1276809529
